spring:
  application:
    name: test-wiremock-server
  main:
    web-application-type: none

wiremock:
  server:
    files: classpath:/__files
    stubs: file:/Users/sonalibora/Documents/mappings

logging:
  level:
    org.springframework.cloud.contract.wiremock: debug
    org.springframework.web.client: debug
    com.github.tomakehurst.wiremock: trace